### ISSUE TITLE
Color names

### ISSUE THREAD

**Issue by iandunn** [iandunn/wordcamp-seattle-2019#9]
@pattyok, what do you think about using [Name That Color](http://chir.ag/projects/name-that-color/) for our color names?

If we just use "blue" then I think we'll run into the problem of having multiple blues (dark blue in footer, lighter blue for text, two other blues in Just For You that I'm not sure what to call, etc).

h/t https://davidwalsh.name/sass-color-variables-dont-suck - that article & the comments discuss a few other techniques as well, but I don't have a lot of experience with any of them, so I'm curious to hear what you think.

**Comment by pattyok** [comment]
@iandunn I typically use blue, blue-light, blue-dark but I know this does get limiting if you have lots of shades in blue in use. 

I'm willing to try the Name that Color Scheme but some of the names that come up in aren't always obvious (like is cerulean really better than blue-light?)...

I also like this approach from the comments... $color-(color name)-(luminance), that allows you to have many shades and you can look at the comp and at least make a guess as to which variable to choose.

**Comment by iandunn** [comment]
Ah, yeah, those are good points 👍 

Another interesting thing from the comments is the idea of [having vars for both color and purpose](https://davidwalsh.name/sass-color-variables-dont-suck#comment-246931), so maybe we'd end up with something like:

```scss
$color-blue-42: hsl(201, 100%, 42%);
$color-blue-90: hsl(201, 100%, 90%);

$color-footer-background: $color-blue-42;

footer {
    background: $color-footer-background;
}
```

What do you think of that?
